### ISSUE TITLE
Broken format?

### ISSUE THREAD

**Issue by jamesmstone** [mrw34/parkrun-to-sqlite#1]
Hi I was just trying to install and use your library. 

https://github.com/jamesmstone/parkrun/blob/main/.github/workflows/scrape.yml#L28-L31

which is essentially a :
```
        pip install parkrun-to-sqlite
        parkrun-to-sqlite 3173185 parkruns.db
```

I am unfortunately getting this error:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/bin/parkrun-to-sqlite", line [8](https://github.com/jamesmstone/parkrun/actions/runs/6368934421/job/17288709438#step:6:9), in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.[10](https://github.com/jamesmstone/parkrun/actions/runs/6368934421/job/17288709438#step:6:11).13/x64/lib/python3.10/site-packages/parkrun_to_sqlite/__main__.py", line 137, in main
    parkruns = get_parkruns(req)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/parkrun_to_sqlite/__main__.py", line 58, in get_parkruns
    for row in reversed(parser.tables[-1])
IndexError: list index out of range
```

https://github.com/jamesmstone/parkrun/actions/runs/6368934421/job/17288709438#step:6:13

Which seems to reference this: 
https://github.com/mrw34/parkrun-to-sqlite/blob/06cc95f025f54db4b30062c6c3916a96198413ef/parkrun_to_sqlite/__main__.py#L39C1-L60C1

My guess is the results format has changed? 

you seem to be loading the last table? `        for row in reversed(parser.tables[-1])`  on this page. https://www.parkrun.org.uk/parkrunner/3173185/all/

which still seems correct?

**Comment by jamesmstone** [comment]
actually , maybe it is just not loading the `html`, so then can't find the tables

**Comment by mrw34** [comment]
> actually , maybe it is just not loading the `html`, so then can't find the tables

That's the mostly likely explanation. I assume it works for you locally?

```sh
$ pip install parkrun-to-sqlite
$ parkrun-to-sqlite 3173185 parkruns.db
$ sqlite3 parkruns.db 'select count(*) from runs'
8
```

If so then the failure of your pipeline is probably because the GitHub-hosted runner is located e.g. in the US. parkrun block requests based on geolocation of source IP address.

**Comment by jamesmstone** [comment]
Thanks, that was indeed the problem!Sorry I was a bit quick to open the issue!

Also, thanks for the repo :runner:
